project_name: pingplop

dist: build/releases

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/app
    binary: pingplop
    ldflags:
      - -w -s -extldflags '-static'
      - -X github.com/riipandi/pingplop/meta.Version={{ .Version }}
      - -X github.com/riipandi/pingplop/meta.BuildDate={{ .Date }}
    env:
      - CGO_ENABLED=0
    goos:
      # - windows
      # - darwin
      - freebsd
      - linux
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - "7"
    ignore:
      - goos: windows
        goarch: arm
      - goos: freebsd
        goarch: arm
      - goos: darwin
        goarch: arm

release:
  draft: true

archives:
  - format: zip
    files:
      - LICENSE*
      - CHANGELOG*

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^web:"
