development:
  dialect: sqlite3
  datasource: build/debug/data/pingplop.db
  dir: migrations
  table: _migrations

production:
  dialect: sqlite3
  datasource: ${DATABASE_URL}
  dir: migrations
  table: _migrations
