# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json

version: '3.8'

services:
  keydb:
    # drop-in replacement for Redis
    image: eqalpha/keydb:latest
    container_name: pingplop_keydb
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - 'keydb_data:/data'
    command: 'keydb-server /etc/keydb/redis.conf --server-threads 2'

  mailpit:
    image: axllent/mailpit:v1.8
    container_name: pingplop_mailpit
    restart: unless-stopped
    volumes:
      - mailpit_data:/data
    ports:
      - '1025:1025' # port the SMTP server should be accessible on
      - '8025:8025' # port the web interface should be accessible on
    environment:
      # https://github.com/axllent/mailpit/wiki/Runtime-options
      TZ: 'Asia/Jakarta'

volumes:
  keydb_data:
    driver: local
  mailpit_data:
    driver: local
