##
# Created by Aris Ripandi (10 Dec 2022)
# See https://fly.io/docs/reference/configuration/ for information about
# how to use this file.
##

app = "pingplop-demo"
primary_region = "sjc"
kill_signal = "SIGINT"
kill_timeout = 5
swap_size_mb = 256
console_command = "/bin/sh"

[build]
  # image = "ghcr.io/pingplop/pingplop:latest"
  dockerfile = "Dockerfile"

[build.args]
  NODE_VERSION = "20"
  GO_VERSION = "1.21"
  BUILD_VERSION = "0.0.1-fly"
  BUILD_DATE = "2023-11-05T20:29:41Z"

[deploy]
  strategy = "immediate"
  # release_command = "/usr/bin/pingplop migrate"

[env]
  PORT = "3080"

[http_service]
  internal_port = 3080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [http_service.concurrency]
    type = "requests"
    soft_limit = 200
    hard_limit = 250

  [http_service.tls_options]
    alpn = ["h2", "http/1.1"]
    versions = ["TLSv1.2", "TLSv1.3"]
    default_self_signed = false

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/api/health"
  protocol = "http"
  tls_skip_verify = true
