# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: CI Actions

on:
  push:
    tags-ignore:
      - '*'
  pull_request:

permissions: read-all

env:
  nodeVersion: 20
  goVersion: '1.21.3'

# Cancel in progress workflows on pull_requests. A Doppler Service Token provides read-only
# access to a single config and is recommended due to its limited access scope.
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test-build:
    # if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run actions/setup-sdk@local
        uses: ./.github/setup-sdk
        with:
          nodeVersion: ${{ env.nodeVersion }}
          goVersion: ${{ env.goVersion }}

      - if: ${{ steps.pnpm-cache.outputs.cache-hit != 'true' }}
        name: Install dependencies and build
        run: |
          pnpm install && pnpm build
          mkdir -p build
          go mod download
          go mod tidy
          go mod vendor
          go build --ldflags="-w -s -extldflags '-static' \
            -X github.com/pingplop/pingplop/meta.Version=$(cat package.json | jq -r .version) \
            -X github.com/pingplop/pingplop/meta.BuildDate=$(date -u +%Y-%m-%dT%H:%M:%SZ)" \
            -a -o build/pingplop cmd/app/main.go
          ls -lha build/
