name: Create Release

on:
  pull_request:
    types: [opened, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  create-release:
    runs-on: ubuntu-22.04
    timeout-minutes: 15
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # - name: Setup PNPM Package Manager
      #   uses: pnpm/action-setup@v2
      #   with:
      #     version: ^7.17
      #     run_install: |
      #       - args: [--global, prettier, husky, lint-staged, tailwindcss]
      #       - args: [--no-frozen-lockfile]

      # - name: Setup Node.js
      #   uses: actions/setup-node@v3
      #   with:
      #     cache: "pnpm"

      # - name: Install dependencies
      #   run: pnpm install

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ">=1.21.3"

      # This step usually is not needed because the /ui/dist is pregenerated locally
      # but its here to ensure that each release embeds the latest admin ui artifacts.
      # If the artificats differs, a "dirty error" is thrown - https://goreleaser.com/errors/dirty/
      # - name: Build Admin dashboard UI
      #   run: npm --prefix=./web ci && npm --prefix=./web run build
      # The prebuilt golangci-lint doesn't support go 1.18+ yet
      # https://github.com/golangci/golangci-lint/issues/2649
      # - name: Run linter
      #   uses: golangci/golangci-lint-action@v3
      # - name: Run tests
      #   run: go test ./...
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
